### ISSUE TITLE
RedstoneEtherCoordsPlayerMem

### ISSUE THREAD

**Issue by ali4z** [SlimeVoid/WirelessRedstone#2]
RedstoneEtherCoordsPlayerMem does not seem to be used.
Needs research into whether or not we can remove this.

**Comment by ali4z** [comment]
Used in:
PacketHandlerWirelessTriangulator.PacketHandlerInput.handleWirelessTriangulator
RedstoneEtherOverrideTriangulator.beforeGetClosestActiveTransmitter

Revisit when we get around to Triangulator addon.

**Comment by Eurymachus** [comment]
Agreed
