### ISSUE TITLE
Block ID

### ISSUE THREAD

**Issue by Keridos** [SlimeVoid/WirelessRedstone#25]
We could change the Standard ID used to be over 255, since the blocks are not supposed to be generated with the worldgen. If we do this, I will try to search for an unused ID for most mods (I run a client with a lot of mods).

**Comment by ali4z** [comment]
Will look into the possibility for this.
Would rather not change the defaults though, as it may cause issues for people with existing worlds. But will be done when needed (when current IDs are vanilla reserved)

**Comment by Eurymachus** [comment]
Completed
