### ISSUE TITLE
MC 1.6.2 Migration

### ISSUE THREAD

**Issue by OldYin** [SlimeVoid/WirelessRedstone#29]
Just for info:

With Optifine installed, this statement in class GuiLib;
public static final ResourceLocation GUI_SMALL =    new ResourceLocation(CoreLib.MOD_ID, GUI_PREFIX + "wifi_small.png"); resolves to the case sensitive path; "assets/WirelessRedstoneCore/textures/gui/" and not "assets/wirelessredstonecore/textures/gui/". The result is that the GUI graphics fail to load.

The mixed case MOD_ID, as defined in CoreLib.java, seemed to be the issue. I do not normally see this issue with Forge + Minecraft alone but have noticed this causing issues for a lot of mods since 1.6.2, particularly with Optifine installed.
To fix it, I left MOD_ID alone but modified GuiLib as below. It's your mod and however you want to address this is fine by me but that's what I did.

I love this mod and needed it in a hurry. Hope you plan to release officially some time soon :-)

Regards,
Alex

package wirelessredstone.core.lib;

public class CoreLib {

```
public static final String MOD_ID = "WirelessRedstoneCore";
public static final String MOD_NAME = "Wireless Redstone";
```

}

package wirelessredstone.core.lib;

import net.minecraft.util.ResourceLocation;

public class GuiLib {
    private static final String L_MOD_ID=CoreLib.MOD_ID.toLowerCase(); 
    private static final String GUI_PREFIX = "textures/gui/";
    public static final ResourceLocation GUI_ON =       new ResourceLocation(L_MOD_ID, GUI_PREFIX + "guiOn.png");
    public static final ResourceLocation GUI_OFF =      new ResourceLocation(L_MOD_ID, GUI_PREFIX + "guiOff.png");
    public static final ResourceLocation GUI_EXIT =     new ResourceLocation(L_MOD_ID, GUI_PREFIX + "wifi_exit.png");
    public static final ResourceLocation GUI_SMALL =    new ResourceLocation(L_MOD_ID, GUI_PREFIX + "wifi_small.png");
    public static final ResourceLocation GUI_MEDIUM =   new ResourceLocation(L_MOD_ID, GUI_PREFIX + "wifi_medium.png");
    public static final ResourceLocation GUI_LARGE =    new ResourceLocation(L_MOD_ID, GUI_PREFIX + "wifi_large.png");
    public static final ResourceLocation GUI_XLARGE =   new ResourceLocation(L_MOD_ID, GUI_PREFIX + "wifi_xlarge.png");
    public static final int GUIID_INVENTORY = 0;
    public static final int GUIID_DEVICE = 1;
}

**Comment by Tarig0** [comment]
Is this still an issue?

**Comment by Eurymachus** [comment]
Doesnt seem so.
