### ISSUE TITLE
Create Add-ons as seperate repos

### ISSUE THREAD

**Issue by Tarig0** [SlimeVoid/WirelessRedstone#31]
I would like to create repos for each add-on and reference the core as a submodule

**Comment by Tarig0** [comment]
This will reflect how forge references FML

**Comment by Eurymachus** [comment]
Best get familiar with python and ant then. So we can create build and install scripts :P

**Comment by Eurymachus** [comment]
Gogo!

**Comment by Eurymachus** [comment]
Actually, There's no reason to use the dependency feature since we can just do it like we use SlimevoidLib.

**Comment by Eurymachus** [comment]
It would be nice if you could have Sub-repos though, Our repo page is littered with repos at the moment

**Comment by Tarig0** [comment]
Python? I live in python :P not really but had to learn it for work once

**Comment by Tarig0** [comment]
Could we create another account much like our archive account? and mention is in the readme

**Comment by Tarig0** [comment]
what we have now is good enough
